#!/bin/bash

while true; do
  cpu_usage=$(top -bn1 | awk '/Cpu/ { print $2}')
  cpu_temp=$(sensors k10temp-pci-00c3|grep Tctl|awk '{print $2}')
  gpu_temp=$(sensors amdgpu-pci-c500|grep edge|awk '{print $2}')
  disk=$(df -h | awk '{ if ($6 == "/home") print $4 }')
  disk_temp=$(sensors nvme-pci-0100|grep Composite|awk '{print $2}')
  memory=$(free -h | awk '(NR==2){ print $4 }')
  wifi=$(cat /sys/class/net/wlp4s0/operstate)
  wired=$(cat /sys/class/net/enp2s0/operstate)
  datetime=$(date +"%F %H:%M:%S")
  echo " CPU usage: ${cpu_usage}% | CPU temp: ${cpu_temp} | GPU temp: ${gpu_temp} | Free memory: ${memory} | Free disk space: ${disk} | Disk temp: ${disk_temp} | Wifi status: ${wifi} | Wired status: ${wired} | ${datetime} "
  sleep 1s
done | /usr/local/bin/dwl 
