#!/bin/bash

while true; do
  cpu_usage=$(top -bn1 | awk '/Cpu/ { print $2}')
  cpu_temp=$(sed 's/000$/°C/' /sys/class/thermal/thermal_zone1/temp)
  disk=$(df -h | awk '{ if ($6 == "/home") print $4 }')
  memory=$(free -h | awk '(NR==2){ print $4 }')
  wifi=$(cat /sys/class/net/wlp4s0/operstate)
  wired=$(cat /sys/class/net/enp2s0/operstate)
  datetime=$(date +"%F %H:%M:%S")
  echo " CPU usage: ${cpu_usage}% | CPU temp: ${cpu_temp} | Free memory: ${memory} | Free disk space: ${disk} | Wifi status: ${wifi} | Wired status: ${wired} | ${datetime} "
  sleep 1s
done | /usr/local/bin/dwl 
